spring:
  datasource:
    url: jdbc:mysql://fitness-bro-dev.creye0kuc4ct.ap-northeast-2.rds.amazonaws.com:3306/fitness-bro
    username: root
    password: fitnessbro12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: tru
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000


logging:
  level:
    org.hibernate.SQL: debug

servlet:
  multipart:
    enabled: true
    maxFileSize: 200MB
    maxRequestSize: 300MB