spring:
  datasource:

    url: jdbc:h2:tcp://localhost/~/fitness-bro
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug


  spring.datasource.url=jdbc:mysql://아이피:3306/데이터베이스?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    spring.datasource.username=아이디
    spring.datasource.password=비밀번호
    
    
    spring.jpa.hibernate.ddl-auto=create // 원래는 데이터베이스에 회원정보를 저장할 테이블을 생성해야 하지만 이걸 통해서 
                                          스프링 부트 entity 클래스 기반으로 테이블을 생성할 수 있다.
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl